version: "3.4"

services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/work
      - ~/.docker-rc.d/:/.docker-rc.d/:ro
    working_dir: /work
    entrypoint: ./docker-entrypoint.sh
    environment:
      BUNDLE_PATH: /work/vendor/bundle
